language: python
os: linux
dist: bionic
python: 3.7
jobs:
  include:
    - name: "docker-compose-build"
      if: branch NOT IN (master, dev) # already covered by docker-compose-test
      services: docker
      script: make build
    - name: "docker-compose-test"
      if: branch IN (master, dev)
      services: docker
      script: 
        - make test
      after_script:
        - ls -la ./data/ # mlflow artifact & tracking data
    - name: "tox"
      env: TOX_PYTHON_ENV=py37
      install:
        - pip install tox-travis
        - pip install codecov
      script:
        - tox -e $TOX_PYTHON_ENV -e lint
      after_success:
        - codecov # submit coverage to https://codecov.io/gh/sertansenturk/cookiecutter-ds-docker/
before_install:
  - pwd
  - ls -la
  - id
  - docker --version
  - pip install -U pip
  - pip install cookiecutter
install:
  -
before_script:
  - cookiecutter --no-input ./ --output-dir ../ repo_name=test-repo author_name=test_author author_email=test_email github_username=test_user description=test_description
  - cd ../test-repo
script:
  - 
after_success:
  - 
after_script:
  - 