language: python
os: linux
dist: bionic
jobs:
  include:
    - name: "Python 3.7"
      python: 3.7
      env: TOX_PYTHON_ENV=py37
before_install:
  - ls -la
  - docker --version
install:
  - pip install -U pip
  - pip install tox-travis
  - pip install codecov
script:
  - tox -e $TOX_PYTHON_ENV -e lint
after_success:
  - codecov # submit coverage to https://codecov.io/gh/sertansenturk/tomato/
