language: python
os: linux
dist: bionic
python: 3.7
env:
  global:
    - COOKIECUTTER_REPO_DIR=..
    - COOKIECUTTER_REPO_NAME=Test Repo
    - COOKIECUTTER_REPO_SLUG=test_repo
    - COOKIECUTTER_PACKAGE_NAME=test_package
    - COOKIECUTTER_AUTHOR_NAME=test_author
    - COOKIECUTTER_AUTHOR_EMAIL=test_email
    - COOKIECUTTER_GITHUB_USERNAME=test_user
    - COOKIECUTTER_DESCRIPTION=test_description
jobs:
  include:
    - name: "docker-compose-build"
      if: branch NOT IN (master, dev) # already covered by docker-compose-test
      services: docker
      script: make build
    - name: "docker-compose-test"
      if: branch IN (master, dev)
      services: docker
      script: 
        - make test
      after_script:
        - ls -la ./data/ # mlflow artifact & tracking data
    - name: "tox"
      env: TOX_PYTHON_ENV=py37
      install:
        - pip install tox-travis
        - pip install codecov
      script:
        - tox -e $TOX_PYTHON_ENV -e lint
      after_success:
        - codecov # submit coverage to https://codecov.io/gh/sertansenturk/cookiecutter-ds-docker/
before_install:
  - pwd
  - ls -la
  - id
  - docker --version
  - pip install -U pip
  - pip install cookiecutter
install:
  -
before_script:
  - >-
    cookiecutter ./
      --no-input
      --output-dir $COOKIECUTTER_REPO_DIR
      repo_name=$COOKIECUTTER_REPO_NAME
      repo_slug=$COOKIECUTTER_REPO_SLUG
      package_name=$COOKIECUTTER_PACKAGE_NAME
      author_name=$COOKIECUTTER_AUTHOR_NAME
      author_email=$COOKIECUTTER_AUTHOR_EMAIL
      github_username=$COOKIECUTTER_GITHUB_USERNAME
      description=$COOKIECUTTER_DESCRIPTION
  - cd $COOKIECUTTER_REPO_DIR/$COOKIECUTTER_REPO_SLUG
script:
  - 
after_success:
  - 
after_script:
  - 
