language: python
os: linux
dist: bionic
jobs:
  include:
    - name: "docker-compose-build"
      if: branch NOT IN (master, dev) # already covered by docker-compose-test
      services: docker
      script: make build
    - name: "docker-compose-test"
      if: branch IN (master, dev)
      services: docker
      script: 
        - make test & # start the stack in the background; runs pytests before Jupyter 
        - sleep 480 # give 6 min for docker build, pytest & Jupyter idle run
        - make down # down the stack
        - make clean-stores # succeeds if the permissions are correct
      after_script:
        - ls -la ./data/ # mlflow artifact & tracking data
    - name: "docker-compose-build-static"
      if: branch IN (master, dev)
      services: docker
      script: make build-static
    - name: "Python 3.7"
      python: 3.7
      before_install:
        - pwd
        - ls -la
        - id
      install:
        - pip install -U pip
        - pip install tox-travis
        - pip install codecov
      script:
        - tox -e $TOX_PYTHON_ENV -e lint
      after_success:
        - codecov # submit coverage to https://codecov.io/gh/sertansenturk/ds-template/        
      env: TOX_PYTHON_ENV=py37
before_install:
  - pwd
  - ls -la
  - id
  - docker --version
install:
  - 
before_script:
  -
script:
  - 
after_success:
  - 
after_script:
  - 