version: '3'
services:
  jupyter:
    build:
      context: ./docker/jupyter
    ports:
      - "8888:8888"
    depends_on: 
      - mlflow
    env_file: 
      - ./docker/jupyter/jupyter.env
    volumes: 
      - ./:/home/jovyan/work
      - ./mlflow:/mlflow
  mlflow:
    build:
      context: ./docker/mlflow
    expose: 
      - "5000"
    ports:
      - "${MLFLOW_TRACKING_SERVER_PORT}:${MLFLOW_TRACKING_SERVER_PORT}"
    depends_on: 
      - postgres
    env_file: 
      - ./docker/mlflow/mlflow.env
      - .env
    volumes:
      - ./mlflow:/mlflow
  postgres:
    build:
      context: ./docker/postgres
    restart: always
    env_file: 
      - ./docker/postgres/postgres.env
      - .env
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres-store:/var/lib/postgresql/data

volumes:
  postgres-store:
